//Automatically generated by generate_design.py script on Thu Feb  7 11:50:18 2013
design = [
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  55.9649435143481, 
  66.20945196975762, 
  27.799472966593008
 ], 
 "group_stds": [
  6.9956179392935125, 
  8.276181496219703, 
  3.474934120824126
 ], 
 "id": "a", 
 "sizes": [
  37, 
  51, 
  63, 
  72, 
  60, 
  59, 
  28, 
  29, 
  26
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 8, 
 "targ_size": 26, 
 "targ_xloc": 427, 
 "targ_yloc": 150, 
 "xlocs": [
  516, 
  351, 
  81, 
  514, 
  89, 
  263, 
  437, 
  432, 
  427
 ], 
 "ylocs": [
  78, 
  152, 
  151, 
  235, 
  326, 
  79, 
  71, 
  315, 
  150
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  51.72971994581145, 
  81.56985104123888, 
  42.90666138398287
 ], 
 "group_stds": [
  6.466214993226432, 
  10.19623138015486, 
  5.363332672997859
 ], 
 "id": "b", 
 "sizes": [
  48, 
  47, 
  44, 
  87, 
  83, 
  87, 
  50, 
  48, 
  50
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 1, 
 "targ_size": 47, 
 "targ_xloc": 259, 
 "targ_yloc": 88, 
 "xlocs": [
  333, 
  259, 
  166, 
  166, 
  523, 
  344, 
  350, 
  424, 
  86
 ], 
 "ylocs": [
  163, 
  88, 
  245, 
  78, 
  238, 
  237, 
  312, 
  163, 
  151
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  64.56687439817381, 
  41.829785889133916, 
  50.024895901102525
 ], 
 "group_stds": [
  8.070859299771726, 
  5.2287232361417395, 
  6.253111987637816
 ], 
 "id": "c", 
 "sizes": [
  62, 
  62, 
  65, 
  46, 
  41, 
  44, 
  54, 
  52, 
  41
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 8, 
 "targ_size": 41, 
 "targ_xloc": 508, 
 "targ_yloc": 241, 
 "xlocs": [
  85, 
  334, 
  434, 
  162, 
  338, 
  507, 
  88, 
  347, 
  508
 ], 
 "ylocs": [
  150, 
  240, 
  81, 
  160, 
  83, 
  166, 
  323, 
  322, 
  241
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  51.89288020419496, 
  19.756948016053776, 
  78.44021556849106
 ], 
 "group_stds": [
  6.48661002552437, 
  2.469618502006722, 
  9.805026946061382
 ], 
 "id": "d", 
 "sizes": [
  49, 
  52, 
  51, 
  20, 
  19, 
  21, 
  92, 
  70, 
  80
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 1, 
 "targ_size": 52, 
 "targ_xloc": 348, 
 "targ_yloc": 70, 
 "xlocs": [
  173, 
  348, 
  521, 
  262, 
  164, 
  423, 
  254, 
  82, 
  517
 ], 
 "ylocs": [
  163, 
  70, 
  159, 
  239, 
  78, 
  158, 
  327, 
  150, 
  319
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  77.53671255412594, 
  33.56463313641842, 
  45.73469836901906
 ], 
 "group_stds": [
  9.692089069265743, 
  4.195579142052303, 
  5.716837296127382
 ], 
 "id": "e", 
 "sizes": [
  76, 
  81, 
  75, 
  30, 
  31, 
  25, 
  41, 
  48, 
  43
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 7, 
 "targ_size": 48, 
 "targ_xloc": 91, 
 "targ_yloc": 152, 
 "xlocs": [
  259, 
  165, 
  180, 
  92, 
  522, 
  174, 
  332, 
  91, 
  343
 ], 
 "ylocs": [
  315, 
  161, 
  329, 
  321, 
  164, 
  82, 
  232, 
  152, 
  312
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  73.17790963614081, 
  26.207330413370443, 
  35.37514298778988
 ], 
 "group_stds": [
  9.147238704517601, 
  3.2759163016713053, 
  4.421892873473735
 ], 
 "id": "f", 
 "sizes": [
  74, 
  65, 
  75, 
  28, 
  28, 
  21, 
  35, 
  38, 
  35
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 8, 
 "targ_size": 35, 
 "targ_xloc": 426, 
 "targ_yloc": 151, 
 "xlocs": [
  78, 
  516, 
  341, 
  247, 
  172, 
  79, 
  259, 
  345, 
  426
 ], 
 "ylocs": [
  153, 
  237, 
  245, 
  310, 
  243, 
  319, 
  85, 
  150, 
  151
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  51.304667248931885, 
  77.77416408705841, 
  27.62375921687088
 ], 
 "group_stds": [
  6.413083406116486, 
  9.721770510882301, 
  3.45296990210886
 ], 
 "id": "g", 
 "sizes": [
  54, 
  61, 
  50, 
  88, 
  76, 
  78, 
  26, 
  27, 
  25
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 6, 
 "targ_size": 26, 
 "targ_xloc": 252, 
 "targ_yloc": 247, 
 "xlocs": [
  427, 
  432, 
  84, 
  512, 
  247, 
  258, 
  252, 
  333, 
  248
 ], 
 "ylocs": [
  324, 
  169, 
  234, 
  73, 
  86, 
  160, 
  247, 
  325, 
  323
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  19.017131228125336, 
  86.29324824805902, 
  56.68717626511884
 ], 
 "group_stds": [
  2.377141403515667, 
  10.786656031007377, 
  7.085897033139855
 ], 
 "id": "h", 
 "sizes": [
  20, 
  22, 
  16, 
  82, 
  85, 
  88, 
  61, 
  67, 
  53
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 6, 
 "targ_size": 61, 
 "targ_xloc": 176, 
 "targ_yloc": 243, 
 "xlocs": [
  434, 
  517, 
  175, 
  430, 
  521, 
  77, 
  176, 
  80, 
  514
 ], 
 "ylocs": [
  323, 
  233, 
  322, 
  157, 
  158, 
  169, 
  243, 
  316, 
  323
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  16.067442144421953, 
  63.11512070993848, 
  31.190007051660178
 ], 
 "group_stds": [
  2.008430268052744, 
  7.88939008874231, 
  3.8987508814575222
 ], 
 "id": "i", 
 "sizes": [
  19, 
  13, 
  18, 
  62, 
  60, 
  76, 
  25, 
  34, 
  34
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 0, 
 "targ_size": 19, 
 "targ_xloc": 177, 
 "targ_yloc": 74, 
 "xlocs": [
  177, 
  516, 
  161, 
  337, 
  427, 
  258, 
  505, 
  436, 
  345
 ], 
 "ylocs": [
  74, 
  323, 
  328, 
  161, 
  72, 
  314, 
  74, 
  324, 
  231
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  80.715971241155, 
  54.58791410244848, 
  79.90424166856337
 ], 
 "group_stds": [
  10.089496405144375, 
  6.82348926280606, 
  9.988030208570422
 ], 
 "id": "j", 
 "sizes": [
  90, 
  66, 
  74, 
  67, 
  50, 
  66, 
  78, 
  48, 
  92
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 8, 
 "targ_size": 92, 
 "targ_xloc": 508, 
 "targ_yloc": 74, 
 "xlocs": [
  514, 
  333, 
  164, 
  87, 
  85, 
  262, 
  343, 
  420, 
  508
 ], 
 "ylocs": [
  312, 
  327, 
  78, 
  234, 
  314, 
  311, 
  240, 
  326, 
  74
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  66.73650816517265, 
  29.96372617963866, 
  64.39842190392339
 ], 
 "group_stds": [
  8.342063520646581, 
  3.7454657724548324, 
  8.049802737990424
 ], 
 "id": "k", 
 "sizes": [
  64, 
  80, 
  70, 
  33, 
  31, 
  31, 
  53, 
  60, 
  56
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 2, 
 "targ_size": 70, 
 "targ_xloc": 508, 
 "targ_yloc": 150, 
 "xlocs": [
  420, 
  514, 
  508, 
  171, 
  250, 
  75, 
  172, 
  85, 
  264
 ], 
 "ylocs": [
  153, 
  80, 
  150, 
  76, 
  79, 
  238, 
  329, 
  82, 
  153
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  68.62352037985187, 
  88.63013101373872, 
  25.925032347042105
 ], 
 "group_stds": [
  8.577940047481484, 
  11.07876637671734, 
  3.240629043380263
 ], 
 "id": "l", 
 "sizes": [
  79, 
  71, 
  75, 
  75, 
  75, 
  86, 
  23, 
  27, 
  29
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 6, 
 "targ_size": 23, 
 "targ_xloc": 431, 
 "targ_yloc": 317, 
 "xlocs": [
  79, 
  434, 
  167, 
  335, 
  505, 
  508, 
  431, 
  266, 
  161
 ], 
 "ylocs": [
  169, 
  85, 
  318, 
  326, 
  239, 
  74, 
  317, 
  151, 
  155
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  74.5533258145032, 
  49.828370251088934, 
  65.79591799493325
 ], 
 "group_stds": [
  9.3191657268129, 
  6.228546281386117, 
  8.224489749366656
 ], 
 "id": "m", 
 "sizes": [
  68, 
  72, 
  78, 
  50, 
  45, 
  50, 
  67, 
  44, 
  81
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 2, 
 "targ_size": 78, 
 "targ_xloc": 425, 
 "targ_yloc": 240, 
 "xlocs": [
  92, 
  262, 
  425, 
  515, 
  165, 
  165, 
  172, 
  420, 
  348
 ], 
 "ylocs": [
  310, 
  79, 
  240, 
  79, 
  153, 
  311, 
  248, 
  167, 
  164
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  15.667007630825012, 
  47.57690644115818, 
  56.88726779536405
 ], 
 "group_stds": [
  1.9583759538531265, 
  5.947113305144772, 
  7.110908474420507
 ], 
 "id": "n", 
 "sizes": [
  16, 
  13, 
  10, 
  51, 
  47, 
  48, 
  52, 
  68, 
  49
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 0, 
 "targ_size": 16, 
 "targ_xloc": 513, 
 "targ_yloc": 83, 
 "xlocs": [
  513, 
  429, 
  92, 
  255, 
  423, 
  257, 
  259, 
  420, 
  343
 ], 
 "ylocs": [
  83, 
  152, 
  246, 
  315, 
  83, 
  236, 
  73, 
  318, 
  314
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  23.47274669264423, 
  58.03080281017924, 
  51.816652667975006
 ], 
 "group_stds": [
  2.9340933365805286, 
  7.253850351272405, 
  6.477081583496876
 ], 
 "id": "o", 
 "sizes": [
  22, 
  22, 
  21, 
  58, 
  46, 
  70, 
  51, 
  64, 
  57
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 1, 
 "targ_size": 22, 
 "targ_xloc": 76, 
 "targ_yloc": 158, 
 "xlocs": [
  248, 
  76, 
  251, 
  428, 
  179, 
  165, 
  250, 
  436, 
  77
 ], 
 "ylocs": [
  159, 
  158, 
  323, 
  77, 
  79, 
  161, 
  248, 
  235, 
  325
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "OrangeRed"
 ], 
 "group_means": [
  55.9649435143481, 
  66.20945196975762, 
  27.799472966593008
 ], 
 "group_stds": [
  6.9956179392935125, 
  8.276181496219703, 
  3.474934120824126
 ], 
 "id": "a", 
 "sizes": [
  37, 
  51, 
  63, 
  72, 
  60, 
  59, 
  28, 
  29, 
  26
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 8, 
 "targ_size": 26, 
 "targ_xloc": 427, 
 "targ_yloc": 150, 
 "xlocs": [
  516, 
  351, 
  81, 
  514, 
  89, 
  263, 
  437, 
  432, 
  427
 ], 
 "ylocs": [
  78, 
  152, 
  151, 
  235, 
  326, 
  79, 
  71, 
  315, 
  150
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "OrangeRed"
 ], 
 "group_means": [
  51.72971994581145, 
  81.56985104123888, 
  42.90666138398287
 ], 
 "group_stds": [
  6.466214993226432, 
  10.19623138015486, 
  5.363332672997859
 ], 
 "id": "b", 
 "sizes": [
  48, 
  47, 
  44, 
  87, 
  83, 
  87, 
  50, 
  48, 
  50
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 1, 
 "targ_size": 47, 
 "targ_xloc": 259, 
 "targ_yloc": 88, 
 "xlocs": [
  333, 
  259, 
  166, 
  166, 
  523, 
  344, 
  350, 
  424, 
  86
 ], 
 "ylocs": [
  163, 
  88, 
  245, 
  78, 
  238, 
  237, 
  312, 
  163, 
  151
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "OrangeRed"
 ], 
 "group_means": [
  64.56687439817381, 
  41.829785889133916, 
  50.024895901102525
 ], 
 "group_stds": [
  8.070859299771726, 
  5.2287232361417395, 
  6.253111987637816
 ], 
 "id": "c", 
 "sizes": [
  62, 
  62, 
  65, 
  46, 
  41, 
  44, 
  54, 
  52, 
  41
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 8, 
 "targ_size": 41, 
 "targ_xloc": 508, 
 "targ_yloc": 241, 
 "xlocs": [
  85, 
  334, 
  434, 
  162, 
  338, 
  507, 
  88, 
  347, 
  508
 ], 
 "ylocs": [
  150, 
  240, 
  81, 
  160, 
  83, 
  166, 
  323, 
  322, 
  241
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  51.89288020419496, 
  19.756948016053776, 
  78.44021556849106
 ], 
 "group_stds": [
  6.48661002552437, 
  2.469618502006722, 
  9.805026946061382
 ], 
 "id": "d", 
 "sizes": [
  49, 
  52, 
  51, 
  20, 
  19, 
  21, 
  92, 
  70, 
  80
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 1, 
 "targ_size": 52, 
 "targ_xloc": 348, 
 "targ_yloc": 70, 
 "xlocs": [
  173, 
  348, 
  521, 
  262, 
  164, 
  423, 
  254, 
  82, 
  517
 ], 
 "ylocs": [
  163, 
  70, 
  159, 
  239, 
  78, 
  158, 
  327, 
  150, 
  319
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  77.53671255412594, 
  33.56463313641842, 
  45.73469836901906
 ], 
 "group_stds": [
  9.692089069265743, 
  4.195579142052303, 
  5.716837296127382
 ], 
 "id": "e", 
 "sizes": [
  76, 
  81, 
  75, 
  30, 
  31, 
  25, 
  41, 
  48, 
  43
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 7, 
 "targ_size": 48, 
 "targ_xloc": 91, 
 "targ_yloc": 152, 
 "xlocs": [
  259, 
  165, 
  180, 
  92, 
  522, 
  174, 
  332, 
  91, 
  343
 ], 
 "ylocs": [
  315, 
  161, 
  329, 
  321, 
  164, 
  82, 
  232, 
  152, 
  312
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "OrangeRed"
 ], 
 "group_means": [
  73.17790963614081, 
  26.207330413370443, 
  35.37514298778988
 ], 
 "group_stds": [
  9.147238704517601, 
  3.2759163016713053, 
  4.421892873473735
 ], 
 "id": "f", 
 "sizes": [
  74, 
  65, 
  75, 
  28, 
  28, 
  21, 
  35, 
  38, 
  35
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 8, 
 "targ_size": 35, 
 "targ_xloc": 426, 
 "targ_yloc": 151, 
 "xlocs": [
  78, 
  516, 
  341, 
  247, 
  172, 
  79, 
  259, 
  345, 
  426
 ], 
 "ylocs": [
  153, 
  237, 
  245, 
  310, 
  243, 
  319, 
  85, 
  150, 
  151
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "OrangeRed", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  51.304667248931885, 
  77.77416408705841, 
  27.62375921687088
 ], 
 "group_stds": [
  6.413083406116486, 
  9.721770510882301, 
  3.45296990210886
 ], 
 "id": "g", 
 "sizes": [
  54, 
  61, 
  50, 
  88, 
  76, 
  78, 
  26, 
  27, 
  25
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 6, 
 "targ_size": 26, 
 "targ_xloc": 252, 
 "targ_yloc": 247, 
 "xlocs": [
  427, 
  432, 
  84, 
  512, 
  247, 
  258, 
  252, 
  333, 
  248
 ], 
 "ylocs": [
  324, 
  169, 
  234, 
  73, 
  86, 
  160, 
  247, 
  325, 
  323
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "OrangeRed", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  19.017131228125336, 
  86.29324824805902, 
  56.68717626511884
 ], 
 "group_stds": [
  2.377141403515667, 
  10.786656031007377, 
  7.085897033139855
 ], 
 "id": "h", 
 "sizes": [
  20, 
  22, 
  16, 
  82, 
  85, 
  88, 
  61, 
  67, 
  53
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 6, 
 "targ_size": 61, 
 "targ_xloc": 176, 
 "targ_yloc": 243, 
 "xlocs": [
  434, 
  517, 
  175, 
  430, 
  521, 
  77, 
  176, 
  80, 
  514
 ], 
 "ylocs": [
  323, 
  233, 
  322, 
  157, 
  158, 
  169, 
  243, 
  316, 
  323
 ]
},
{
 "colors": [
  "RoyalBlue", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "OrangeRed", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  16.067442144421953, 
  63.11512070993848, 
  31.190007051660178
 ], 
 "group_stds": [
  2.008430268052744, 
  7.88939008874231, 
  3.8987508814575222
 ], 
 "id": "i", 
 "sizes": [
  19, 
  13, 
  18, 
  62, 
  60, 
  76, 
  25, 
  34, 
  34
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 0, 
 "targ_size": 19, 
 "targ_xloc": 177, 
 "targ_yloc": 74, 
 "xlocs": [
  177, 
  516, 
  161, 
  337, 
  427, 
  258, 
  505, 
  436, 
  345
 ], 
 "ylocs": [
  74, 
  323, 
  328, 
  161, 
  72, 
  314, 
  74, 
  324, 
  231
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "RoyalBlue", 
  "OrangeRed"
 ], 
 "group_means": [
  80.715971241155, 
  54.58791410244848, 
  79.90424166856337
 ], 
 "group_stds": [
  10.089496405144375, 
  6.82348926280606, 
  9.988030208570422
 ], 
 "id": "j", 
 "sizes": [
  90, 
  66, 
  74, 
  67, 
  50, 
  66, 
  78, 
  48, 
  92
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 8, 
 "targ_size": 92, 
 "targ_xloc": 508, 
 "targ_yloc": 74, 
 "xlocs": [
  514, 
  333, 
  164, 
  87, 
  85, 
  262, 
  343, 
  420, 
  508
 ], 
 "ylocs": [
  312, 
  327, 
  78, 
  234, 
  314, 
  311, 
  240, 
  326, 
  74
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  66.73650816517265, 
  29.96372617963866, 
  64.39842190392339
 ], 
 "group_stds": [
  8.342063520646581, 
  3.7454657724548324, 
  8.049802737990424
 ], 
 "id": "k", 
 "sizes": [
  64, 
  80, 
  70, 
  33, 
  31, 
  31, 
  53, 
  60, 
  56
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 2, 
 "targ_size": 70, 
 "targ_xloc": 508, 
 "targ_yloc": 150, 
 "xlocs": [
  420, 
  514, 
  508, 
  171, 
  250, 
  75, 
  172, 
  85, 
  264
 ], 
 "ylocs": [
  153, 
  80, 
  150, 
  76, 
  79, 
  238, 
  329, 
  82, 
  153
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "OrangeRed", 
  "RoyalBlue", 
  "RoyalBlue"
 ], 
 "group_means": [
  68.62352037985187, 
  88.63013101373872, 
  25.925032347042105
 ], 
 "group_stds": [
  8.577940047481484, 
  11.07876637671734, 
  3.240629043380263
 ], 
 "id": "l", 
 "sizes": [
  79, 
  71, 
  75, 
  75, 
  75, 
  86, 
  23, 
  27, 
  29
 ], 
 "targ_color": "OrangeRed", 
 "targ_index": 6, 
 "targ_size": 23, 
 "targ_xloc": 431, 
 "targ_yloc": 317, 
 "xlocs": [
  79, 
  434, 
  167, 
  335, 
  505, 
  508, 
  431, 
  266, 
  161
 ], 
 "ylocs": [
  169, 
  85, 
  318, 
  326, 
  239, 
  74, 
  317, 
  151, 
  155
 ]
},
{
 "colors": [
  "OrangeRed", 
  "OrangeRed", 
  "RoyalBlue", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  74.5533258145032, 
  49.828370251088934, 
  65.79591799493325
 ], 
 "group_stds": [
  9.3191657268129, 
  6.228546281386117, 
  8.224489749366656
 ], 
 "id": "m", 
 "sizes": [
  68, 
  72, 
  78, 
  50, 
  45, 
  50, 
  67, 
  44, 
  81
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 2, 
 "targ_size": 78, 
 "targ_xloc": 425, 
 "targ_yloc": 240, 
 "xlocs": [
  92, 
  262, 
  425, 
  515, 
  165, 
  165, 
  172, 
  420, 
  348
 ], 
 "ylocs": [
  310, 
  79, 
  240, 
  79, 
  153, 
  311, 
  248, 
  167, 
  164
 ]
},
{
 "colors": [
  "RoyalBlue", 
  "OrangeRed", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  15.667007630825012, 
  47.57690644115818, 
  56.88726779536405
 ], 
 "group_stds": [
  1.9583759538531265, 
  5.947113305144772, 
  7.110908474420507
 ], 
 "id": "n", 
 "sizes": [
  16, 
  13, 
  10, 
  51, 
  47, 
  48, 
  52, 
  68, 
  49
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 0, 
 "targ_size": 16, 
 "targ_xloc": 513, 
 "targ_yloc": 83, 
 "xlocs": [
  513, 
  429, 
  92, 
  255, 
  423, 
  257, 
  259, 
  420, 
  343
 ], 
 "ylocs": [
  83, 
  152, 
  246, 
  315, 
  83, 
  236, 
  73, 
  318, 
  314
 ]
},
{
 "colors": [
  "OrangeRed", 
  "RoyalBlue", 
  "OrangeRed", 
  "LimeGreen", 
  "LimeGreen", 
  "LimeGreen", 
  "RoyalBlue", 
  "OrangeRed", 
  "RoyalBlue"
 ], 
 "group_means": [
  23.47274669264423, 
  58.03080281017924, 
  51.816652667975006
 ], 
 "group_stds": [
  2.9340933365805286, 
  7.253850351272405, 
  6.477081583496876
 ], 
 "id": "o", 
 "sizes": [
  22, 
  22, 
  21, 
  58, 
  46, 
  70, 
  51, 
  64, 
  57
 ], 
 "targ_color": "RoyalBlue", 
 "targ_index": 1, 
 "targ_size": 22, 
 "targ_xloc": 76, 
 "targ_yloc": 158, 
 "xlocs": [
  248, 
  76, 
  251, 
  428, 
  179, 
  165, 
  250, 
  436, 
  77
 ], 
 "ylocs": [
  159, 
  158, 
  323, 
  77, 
  79, 
  161, 
  248, 
  235, 
  325
 ]
}
]